
services:

  make:
    image: ${DOCKERHUB_USERNAME}/make:${MD5_MAKE}
    build:
      context: ./dev/docker/make
      dockerfile: Dockerfile
      tags:
        - latest
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir

  bash:
    image: ${DOCKERHUB_USERNAME}/bash:${MD5_BASH}
    build:
      context: dev/docker/bash
      dockerfile: Dockerfile
      tags:
        - latest
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir

  opentofu:
    image: ${DOCKERHUB_USERNAME}/opentofu:${MD5_OPENTOFU}
    build:
      context: ./dev/docker/opentofu
      dockerfile: Dockerfile
      tags:
        - latest
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        MD5_BASH: ${MD5_BASH}
        OPENTOFU_RELEASE: ${OPENTOFU_RELEASE}


