
services:

  make:
    image: ${DOCKERHUB_USERNAME}/make:${MAKE_CHECKSUM}
    build:
      context: ./dev/docker/make
      dockerfile: Dockerfile
      tags:
        - latest
        - ${MAKE_CHECKSUM}
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        MAKE_CHECKSUM: ${MAKE_CHECKSUM}
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir
      - ${DOCKER_HOST_MAP}

  bash:
    image: ${DOCKERHUB_USERNAME}/bash:${BASH_CHECKSUM}
    build:
      context: dev/docker/bash
      dockerfile: Dockerfile
      tags:
        - latest
        - ${BASH_CHECKSUM}
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        BASH_CHECKSUM: ${BASH_CHECKSUM}
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir
      - ${DOCKER_HOST_MAP}

  node_semantic_release:
    image: ${DOCKERHUB_USERNAME}/node-semantic-release:${NODE_SEMANTIC_RELEASE_CHECKSUM}
    build:
      context: ./dev/docker/node_semantic_release
      dockerfile: Dockerfile
      tags:
        - latest
        - ${NODE_SEMANTIC_RELEASE_CHECKSUM}
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        BASH_CHECKSUM: ${BASH_CHECKSUM}
        NODE_SEMANTIC_RELEASE_CHECKSUM: ${NODE_SEMANTIC_RELEASE_CHECKSUM}
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir
      - ${DOCKER_HOST_MAP}

  opentofu:
    image: ${DOCKERHUB_USERNAME}/opentofu:${OPENTOFU_CHECKSUM}
    build:
      context: ./dev/docker/opentofu
      dockerfile: Dockerfile
      tags:
        - latest
        - ${OPENTOFU_CHECKSUM}
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        BASH_CHECKSUM: ${BASH_CHECKSUM}
        OPENTOFU_RELEASE: ${OPENTOFU_RELEASE}
        OPENTOFU_CHECKSUM: ${OPENTOFU_CHECKSUM}
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir
      - ${DOCKER_HOST_MAP}
