
services:

  make:
    image: ${DOCKERHUB_USERNAME}/make:${MD5_MAKE}
    build:
      context: ./dev/docker/make
      dockerfile: Dockerfile
      tags:
        - latest
        - ${MD5_MAKE}
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        MD5_MAKE: ${MD5_MAKE}
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir

  bash:
    image: ${DOCKERHUB_USERNAME}/bash:${MD5_BASH}
    build:
      context: dev/docker/bash
      dockerfile: Dockerfile
      tags:
        - latest
        - ${MD5_BASH}
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        MD5_BASH: ${MD5_BASH}
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir

  node_semantic_release:
    image: ${DOCKERHUB_USERNAME}/node-semantic-release:${MD5_NODE_SEMANTIC_RELEASE}
    build:
      context: ./dev/docker/node_semantic_release
      dockerfile: Dockerfile
      tags:
        - latest
        - ${MD5_NODE_SEMANTIC_RELEASE}
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        MD5_BASH: ${MD5_BASH}
        MD5_NODE_SEMANTIC_RELEASE: ${MD5_NODE_SEMANTIC_RELEASE}
    volumes:
      - ${HOST_PROJECT_PATH}:/workdir

  opentofu:
    image: ${DOCKERHUB_USERNAME}/opentofu:${MD5_OPENTOFU}
    build:
      context: ./dev/docker/opentofu
      dockerfile: Dockerfile
      tags:
        - latest
        - ${MD5_OPENTOFU}
      args:
        DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
        MD5_BASH: ${MD5_BASH}
        OPENTOFU_RELEASE: ${OPENTOFU_RELEASE}
        MD5_OPENTOFU: ${MD5_OPENTOFU}
