on:
  push:
    branches:
      - main

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.FOLDERS }}

    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          FOLDERS=$(find dev/docker -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n")[:-1]')
          echo "FOLDERS=$FOLDERS" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    strategy:
      matrix:
        folder: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./dev/docker/${{ matrix.folder }}
          file: ./dev/docker/${{ matrix.folder }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.folder }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.folder }}:${{ github.sha }}
