ANTORA_CHECKSUM=bc94f2be
ANTORA_VERSION=1
BASH_CHECKSUM=513d5ef3
BASH_VERSION=129
DEVTOOLS_JDK21_NODEJS24_CHECKSUM=fdb82722
DEVTOOLS_JDK21_NODEJS24_VERSION=30
MAKE_CHECKSUM=b19cc79e
MAKE_VERSION=138
NODE_SEMANTIC_RELEASE_CHECKSUM=6b6e0606
NODE_SEMANTIC_RELEASE_VERSION=132
OPENTOFU_CHECKSUM=f9cf7c9e
OPENTOFU_VERSION=99
QUARKUS_CHECKSUM=e9d73662
QUARKUS_VERSION=134
