ANTORA_CHECKSUM=3655ea16
ANTORA_VERSION=3
BASH_CHECKSUM=2f3715c0
BASH_VERSION=130
DEVTOOLS_JDK21_NODEJS24_CHECKSUM=6c20cf73
DEVTOOLS_JDK21_NODEJS24_VERSION=31
DEVTOOLS_JDK25_NODEJS24_CHECKSUM=260dfb07
DEVTOOLS_JDK25_NODEJS24_VERSION=1
MAKE_CHECKSUM=7ffd6535
MAKE_VERSION=139
NODE_SEMANTIC_RELEASE_CHECKSUM=8b30b755
NODE_SEMANTIC_RELEASE_VERSION=133
OPENTOFU_CHECKSUM=f9cf7c9e
OPENTOFU_VERSION=99
QUARKUS_CHECKSUM=4266a775
QUARKUS_VERSION=135
